export const backendContractTemplate = {
  contracts: [
    {
      id: "contract_sample_001",
      contractHash: "0xsamplecontracthash",
      name: "Sample AI Service Agreement",
      projectType: "api_rental",
      description: "Reference contract illustrating all supported escrow options and metadata.",
      currentStage: "Signatures Pending",
      flowType: "execution",
      jurisdiction: {
        country: "India",
        countryCode: "IN",
        legalFramework: "Indian Contract Act, 1872",
        disputeResolution: "On-chain arbitration via Pacter Arbitration Network",
        applicableLaws: ["Indian Contract Act", "Information Technology Act", "Goods and Services Tax Act"],
        timezone: "Asia/Kolkata"
      },
      parties: {
        client: {
          name: "Acme Compute Pvt Ltd",
          email: "compute-ops@acme.com",
          walletAddress: "0x1111111111111111111111111111111111111111",
          role: "CLIENT",
          location: {
            country: "India",
            state: "Maharashtra",
            city: "Mumbai"
          }
        },
        freelancer: {
          name: "Nova GPU Services",
          email: "support@novagpu.ai",
          walletAddress: "0x2222222222222222222222222222222222222222",
          role: "FREELANCER",
          skills: ["GPU inference", "Model serving", "SLA monitoring"],
          location: {
            country: "India",
            state: "Karnataka",
            city: "Bengaluru"
          }
        }
      },
      signatures: {
        client: {
          signed: false,
          signedAt: null,
          signature: null
        },
        freelancer: {
          signed: false,
          signedAt: null,
          signature: null
        },
        bothSigned: false
      },
      escrow: {
        amounts: {
          inr: {
            totalAmount: "250000",
            currency: "INR",
            exchangeRateAt: "2025-10-08T10:00:00.000Z",
            exchangeRate: "85.00"
          },
          "0G": {
            totalAmount: "2941",
            currency: "0G",
            network: "0g-testnet"
          }
        },
        contractAddress: "0x3333333333333333333333333333333333333333",
        deposit: {
          deposited: false,
          depositedAmount: "0",
          depositedAt: null,
          transactionHash: null
        },
        fees: {
          platformFee: {
            inr: "6250",
            zeroG: "74"
          },
          storageFee: {
            inr: "1250",
            zeroG: "15"
          },
          totalFees: {
            inr: "7500",
            zeroG: "89"
          }
        }
      },
      storage: {
        contractDocument: {
          rootHash: "0xcontractdocumenthash",
          fileName: "contract_sample_001_signed.pdf",
          uploadedAt: null,
          uploadedBy: null,
          fileSize: "0"
        }
      },
      projectDetails: {
        deliverables: ["Dedicated inference endpoint", "SLA dashboard", "Weekly performance reports"],
        timeline: "90 days",
        startDate: "2025-10-10",
        endDate: "2026-01-08"
      },
      contractOptions: {
        escrowType: "time_locked_inference",
        arbitrationPreference: "Pacter Arbitration Network (default)",
        arbitrationContract: "0x4444444444444444444444444444444444444444",
        vaultOptIn: true
      },
      precompiledContract: {
        key: "milestoneEscrow",
        displayName: "Milestone Escrow (AI Agent Verified)",
        targetNetwork: "0g-testnet",
        deploymentStatus: "not_deployed",
        constructorParameters: {
          client: "0x1111111111111111111111111111111111111111",
          freelancer: "0x2222222222222222222222222222222222222222",
          agent: "0x5555555555555555555555555555555555555555",
          arbitration: "0x4444444444444444444444444444444444444444",
          vault: "0x3333333333333333333333333333333333333333",
          storageFeeWei: "10000000000000000"
        },
        artifactStatus: {
          abi: "pending",
          bytecode: "pending"
        }
      },
      serviceMonitoring: {
        serviceDuration: "120 hours of GPU runtime",
        apiEndpoint: "https://api.novagpu.ai/v1/inference",
        uptimeSLA: "99.5% availability, <150ms p95 latency"
      },
      financialInfo: {
        basePaymentInInr: "250000",
        basePaymentInZeroG: "2941",
        escrowYieldRate: "1%",
        computedYieldShare: {
          client: "90%",
          freelancer: "10%"
        }
      },
      legalContract: {
        contractText: "Reference legal contract text generated by Pacter AI.",
        generatedAt: "2025-10-10T08:00:00.000Z",
        generatedBy: "0G_Compute_TEE",
        storageRootHash: "0xlegalroot",
        verificationProof: {
          type: "TEE",
          hash: "0xverificationhash",
          timestamp: "2025-10-10T08:00:00.000Z"
        }
      },
      milestones: [
        {
          id: "contract_sample_001_milestone_001",
          number: 1,
          description: "Provisioning and onboarding",
          amounts: {
            inr: "50000",
            zeroG: "588"
          },
          dueDate: "2025-10-20",
          status: "PENDING",
          deliverable: {
            type: "inference_setup",
            required: ["Dedicated endpoint URL", "API access tokens", "Monitoring dashboard"],
            submitted: false,
            submittedAt: null,
            submissionLinks: [],
            storage: null
          },
          verification: {
            agentVerified: false,
            verifiedAt: null,
            verificationNote: ""
          },
          review: {
            clientReviewed: false,
            reviewedAt: null,
            approved: null,
            feedback: "",
            revisionRequested: false,
            revisionCount: 0
          },
          payment: {
            released: false,
            releasedAt: null,
            transactionHash: null
          }
        }
      ],
      currentMilestone: null,
      agentInfo: {
        iNFTContractAddress: "0x5555555555555555555555555555555555555555",
        iNFTTokenId: "90001",
        lastAction: null
      },
      stageHistory: [
        {
          stage: "Jurisdiction Selected",
          timestamp: "2025-10-10T08:00:00.000Z",
          triggeredBy: "user",
          note: "India selected as jurisdiction"
        },
        {
          stage: "Information Complete",
          timestamp: "2025-10-10T08:05:00.000Z",
          triggeredBy: "system",
          note: "All required fields collected via graph loop"
        },
        {
          stage: "Signatures Pending",
          timestamp: "2025-10-10T08:06:00.000Z",
          triggeredBy: "system",
          note: "Contract generated and awaiting signatures"
        }
      ],
      shareableLink: "https://pacter.com/contracts/contract_sample_001",
      createdAt: "2025-10-10T08:00:00.000Z",
      lastUpdated: "2025-10-10T08:06:00.000Z",
      status: "ACTIVE"
    }
  ]
};
